In [1]:
import numpy as np
import pandas as pd

In [2]:
list1 ={
    "name": ['Alice', 'Bob', 'Charlie', 'David'],
    "age": [24, 27, 22, 32],
    "city": ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

In [3]:
li = pd.DataFrame(list1)
print(li)

      name  age         city
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [4]:
li.to_csv('man.csv')

In [5]:
li.head(1)

    name  age      city
0  Alice   24  New York

In [6]:
li.tail(3)

      name  age         city
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [7]:
li.describe()

             age
count   4.000000
mean   26.250000
std     4.349329
min    22.000000
25%    23.500000
50%    25.500000
75%    28.250000
max    32.000000

In [8]:
tmp = pd.read_csv('man - Copy.csv')
tmp

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,name,age,city
0,0,0,0,0,Alice,50,New York
1,1,1,1,1,Bob,27,Los Angeles
2,2,2,2,2,max,22,Chicago
3,3,3,3,3,David,32,Houston

In [9]:
tmp ['age'][0] = 50

C:\Users\AM\AppData\Local\Temp\ipykernel_2524\4071321210.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  tmp ['age'][0] = 50
C:\Users\AM\AppData\Local\Temp\ipykernel_2524\4071321210.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp ['age'][0] = 50

In [10]:
tmp

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,name,age,city
0,0,0,0,0,Alice,50,New York
1,1,1,1,1,Bob,27,Los Angeles
2,2,2,2,2,max,22,Chicago
3,3,3,3,3,David,32,Houston

In [11]:
tmp ['name'][2] = 'max'
tmp

C:\Users\AM\AppData\Local\Temp\ipykernel_2524\3165644282.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  tmp ['name'][2] = 'max'
C:\Users\AM\AppData\Local\Temp\ipykernel_2524\3165644282.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp ['name'][2] = 'max'

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,name,age,city
0,0,0,0,0,Alice,50,New York
1,1,1,1,1,Bob,27,Los Angeles
2,2,2,2,2,max,22,Chicago
3,3,3,3,3,David,32,Houston

In [12]:
tmp.to_csv('man - Copy.csv')

In [13]:
newdf = pd.DataFrame(np.random.rand(15,5), index=np.arange(15))
newdf

           0         1         2         3         4
0   0.022465  0.538951  0.103627  0.708337  0.961679
1   0.233810  0.938187  0.249717  0.145294  0.576153
2   0.953235  0.737676  0.430252  0.139942  0.772365
3   0.884765  0.036720  0.323823  0.355740  0.532232
4   0.355562  0.003602  0.378456  0.823788  0.289156
5   0.483842  0.829193  0.050827  0.181338  0.904056
6   0.932941  0.137502  0.786737  0.826932  0.035997
7   0.229671  0.236777  0.555955  0.125188  0.474228
8   0.266915  0.666370  0.229753  0.694966  0.684549
9   0.127474  0.111716  0.345796  0.683976  0.936347
10  0.224829  0.673398  0.617543  0.741872  0.689492
11  0.654127  0.176687  0.424763  0.733136  0.804087
12  0.537105  0.196522  0.462256  0.771644  0.930494
13  0.420670  0.252570  0.241395  0.778115  0.632463
14  0.973436  0.361222  0.551311  0.739626  0.948173

In [14]:
newdf.head()

          0         1         2         3         4
0  0.022465  0.538951  0.103627  0.708337  0.961679
1  0.233810  0.938187  0.249717  0.145294  0.576153
2  0.953235  0.737676  0.430252  0.139942  0.772365
3  0.884765  0.036720  0.323823  0.355740  0.532232
4  0.355562  0.003602  0.378456  0.823788  0.289156

In [15]:
type(newdf)

pandas.core.frame.DataFrame

In [16]:
type(newdf)

pandas.core.frame.DataFrame

In [17]:
newdf.describe()

               0          1          2          3          4
count  15.000000  15.000000  15.000000  15.000000  15.000000
mean    0.486723   0.393140   0.383481   0.563326   0.678098
std     0.322462   0.308736   0.196597   0.281139   0.267078
min     0.022465   0.003602   0.050827   0.125188   0.035997
25%     0.231741   0.157095   0.245556   0.268539   0.554193
50%     0.420670   0.252570   0.378456   0.708337   0.689492
75%     0.769446   0.669884   0.506783   0.756758   0.917275
max     0.973436   0.938187   0.786737   0.826932   0.961679

In [18]:
newdf [0][0] = 'ronak'

C:\Users\AM\AppData\Local\Temp\ipykernel_2524\3531141389.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf [0][0] = 'ronak'
C:\Users\AM\AppData\Local\Temp\ipykernel_2524\3531141389.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'ronak' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf [0][0] = 'ronak'

In [19]:
newdf

           0         1         2         3         4
0      ronak  0.538951  0.103627  0.708337  0.961679
1    0.23381  0.938187  0.249717  0.145294  0.576153
2   0.953235  0.737676  0.430252  0.139942  0.772365
3   0.884765  0.036720  0.323823  0.355740  0.532232
4   0.355562  0.003602  0.378456  0.823788  0.289156
5   0.483842  0.829193  0.050827  0.181338  0.904056
6   0.932941  0.137502  0.786737  0.826932  0.035997
7   0.229671  0.236777  0.555955  0.125188  0.474228
8   0.266915  0.666370  0.229753  0.694966  0.684549
9   0.127474  0.111716  0.345796  0.683976  0.936347
10  0.224829  0.673398  0.617543  0.741872  0.689492
11  0.654127  0.176687  0.424763  0.733136  0.804087
12  0.537105  0.196522  0.462256  0.771644  0.930494
13   0.42067  0.252570  0.241395  0.778115  0.632463
14  0.973436  0.361222  0.551311  0.739626  0.948173

In [20]:
newdf.index

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype='int64')

In [21]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,ronak,0.23381,0.953235,0.884765,0.355562,0.483842,0.932941,0.229671,0.266915,0.127474,0.224829,0.654127,0.537105,0.42067,0.973436
1,0.538951,0.938187,0.737676,0.03672,0.003602,0.829193,0.137502,0.236777,0.66637,0.111716,0.673398,0.176687,0.196522,0.25257,0.361222
2,0.103627,0.249717,0.430252,0.323823,0.378456,0.050827,0.786737,0.555955,0.229753,0.345796,0.617543,0.424763,0.462256,0.241395,0.551311
3,0.708337,0.145294,0.139942,0.35574,0.823788,0.181338,0.826932,0.125188,0.694966,0.683976,0.741872,0.733136,0.771644,0.778115,0.739626
4,0.961679,0.576153,0.772365,0.532232,0.289156,0.904056,0.035997,0.474228,0.684549,0.936347,0.689492,0.804087,0.930494,0.632463,0.948173

In [22]:
newdf

           0         1         2         3         4
0      ronak  0.538951  0.103627  0.708337  0.961679
1    0.23381  0.938187  0.249717  0.145294  0.576153
2   0.953235  0.737676  0.430252  0.139942  0.772365
3   0.884765  0.036720  0.323823  0.355740  0.532232
4   0.355562  0.003602  0.378456  0.823788  0.289156
5   0.483842  0.829193  0.050827  0.181338  0.904056
6   0.932941  0.137502  0.786737  0.826932  0.035997
7   0.229671  0.236777  0.555955  0.125188  0.474228
8   0.266915  0.666370  0.229753  0.694966  0.684549
9   0.127474  0.111716  0.345796  0.683976  0.936347
10  0.224829  0.673398  0.617543  0.741872  0.689492
11  0.654127  0.176687  0.424763  0.733136  0.804087
12  0.537105  0.196522  0.462256  0.771644  0.930494
13   0.42067  0.252570  0.241395  0.778115  0.632463
14  0.973436  0.361222  0.551311  0.739626  0.948173

In [23]:
newdf.head()

          0         1         2         3         4
0     ronak  0.538951  0.103627  0.708337  0.961679
1   0.23381  0.938187  0.249717  0.145294  0.576153
2  0.953235  0.737676  0.430252  0.139942  0.772365
3  0.884765  0.036720  0.323823  0.355740  0.532232
4  0.355562  0.003602  0.378456  0.823788  0.289156

In [24]:
newdf.sort_index(axis=0, ascending=False)

           0         1         2         3         4
14  0.973436  0.361222  0.551311  0.739626  0.948173
13   0.42067  0.252570  0.241395  0.778115  0.632463
12  0.537105  0.196522  0.462256  0.771644  0.930494
11  0.654127  0.176687  0.424763  0.733136  0.804087
10  0.224829  0.673398  0.617543  0.741872  0.689492
9   0.127474  0.111716  0.345796  0.683976  0.936347
8   0.266915  0.666370  0.229753  0.694966  0.684549
7   0.229671  0.236777  0.555955  0.125188  0.474228
6   0.932941  0.137502  0.786737  0.826932  0.035997
5   0.483842  0.829193  0.050827  0.181338  0.904056
4   0.355562  0.003602  0.378456  0.823788  0.289156
3   0.884765  0.036720  0.323823  0.355740  0.532232
2   0.953235  0.737676  0.430252  0.139942  0.772365
1    0.23381  0.938187  0.249717  0.145294  0.576153
0      ronak  0.538951  0.103627  0.708337  0.961679

In [25]:
newdf.head()

          0         1         2         3         4
0     ronak  0.538951  0.103627  0.708337  0.961679
1   0.23381  0.938187  0.249717  0.145294  0.576153
2  0.953235  0.737676  0.430252  0.139942  0.772365
3  0.884765  0.036720  0.323823  0.355740  0.532232
4  0.355562  0.003602  0.378456  0.823788  0.289156

In [26]:
newdf.loc[1,2]

np.float64(0.24971672717859017)

In [27]:
newdf.loc[1,2]=128

In [28]:
newdf.head()

          0         1           2         3         4
0     ronak  0.538951    0.103627  0.708337  0.961679
1   0.23381  0.938187  128.000000  0.145294  0.576153
2  0.953235  0.737676    0.430252  0.139942  0.772365
3  0.884765  0.036720    0.323823  0.355740  0.532232
4  0.355562  0.003602    0.378456  0.823788  0.289156

In [29]:
newdf.loc[(newdf[2]>0.3) & (newdf[3]<0.4)]

          0         1           2         3         4
1   0.23381  0.938187  128.000000  0.145294  0.576153
2  0.953235  0.737676    0.430252  0.139942  0.772365
3  0.884765  0.036720    0.323823  0.355740  0.532232
7  0.229671  0.236777    0.555955  0.125188  0.474228

In [30]:
newdf.head()

          0         1           2         3         4
0     ronak  0.538951    0.103627  0.708337  0.961679
1   0.23381  0.938187  128.000000  0.145294  0.576153
2  0.953235  0.737676    0.430252  0.139942  0.772365
3  0.884765  0.036720    0.323823  0.355740  0.532232
4  0.355562  0.003602    0.378456  0.823788  0.289156

In [31]:
newdf.iloc[0:3,0:2]

          0         1
0     ronak  0.538951
1   0.23381  0.938187
2  0.953235  0.737676

In [32]:
newdf.iloc[:,[0,2,4]]

           0           2         4
0      ronak    0.103627  0.961679
1    0.23381  128.000000  0.576153
2   0.953235    0.430252  0.772365
3   0.884765    0.323823  0.532232
4   0.355562    0.378456  0.289156
5   0.483842    0.050827  0.904056
6   0.932941    0.786737  0.035997
7   0.229671    0.555955  0.474228
8   0.266915    0.229753  0.684549
9   0.127474    0.345796  0.936347
10  0.224829    0.617543  0.689492
11  0.654127    0.424763  0.804087
12  0.537105    0.462256  0.930494
13   0.42067    0.241395  0.632463
14  0.973436    0.551311  0.948173

In [33]:
newdf.iloc[[0,2,6],[1,4]]

          1         4
0  0.538951  0.961679
2  0.737676  0.772365
6  0.137502  0.035997

In [34]:
df = pd.DataFrame(np.random.randn(6,4), index=list('abcdef'), columns=list('WXYZ'))

In [35]:
df.describe()

              W         X         Y         Z
count  6.000000  6.000000  6.000000  6.000000
mean   0.018587  0.108668  0.406797 -0.438109
std    0.626978  0.810256  0.467012  0.846022
min   -0.707307 -0.908314 -0.347979 -1.820052
25%   -0.355313 -0.565362  0.301755 -0.778964
50%   -0.037042  0.264396  0.370084 -0.362458
75%    0.180424  0.734342  0.636889  0.141168
max    1.101402  0.982486  1.043792  0.525068